import com.liu.drools.entity.State

rule "A to B"
    when
        State(name == "A", state == State.FINISHED )
         b : State(name == "B", state == State.NOTRUN )

    then
        System.out.println(b.getName() + " finished" );
        b.setState( State.FINISHED );
end


rule "B to C"
    salience 10
    when
        State(name == "B", state == State.FINISHED )
        c : State(name == "C", state == State.NOTRUN )
    then
        System.out.println(c.getName() + " finished" );
        c.setState( State.FINISHED );
end